[package]
name         = "securitization"
version      = "1.0.0"
edition      = "2024.beta"
license      = "MIT"
authors      = ["IOTA Securitization Protocol"]
 
[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/testnet" }
spv  = { local = "../spv" }
 
[addresses]
securitization = "0x0"
spv = "0x1"